services:
  - type: web
    name: notes-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn notes_app.wsgi
    envVars:
      - key: DATABASE_URL
        value: postgres://your_user:your_password@your_host:5432/your_db_name
    preDeployCommand: python manage.py migrate
